# Generated by Django 3.0.6 on 2020-05-25 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('writter', models.CharField(default='', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('contant', models.TextField(max_length=5000)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('view', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
        migrations.CreateModel(
            name='BlogCommet',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(default='', max_length=250)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.BlogCommet')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Blogpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
